Initial Packages and Domain
patrickhacens/mal_crucible pull request #18
Opened 2022-03-24 16:54 UTC by lucnascimento98

2022-03-25 16:01 UTC, patrickhacens requested changes

2022-03-25 16:01 UTC, patrickhacens commented on src/MyAnimeList/MyAnimeList/RawData/watching_status.csv
> +status, description
Os csv deveriam estar fora do src, inclusive talvez não deveria estar nesse repositório

2022-03-25 16:01 UTC, patrickhacens commented on src/MyAnimeList/MyAnimeList/Domain/CsvDomain/animelist.cs
> +public class animelist
Casing

2022-03-25 16:01 UTC, patrickhacens commented on src/MyAnimeList/MyAnimeList/Domain/CsvDomain/animeraw.cs
> +public class animeraw
Casing

2022-03-25 16:01 UTC, patrickhacens commented on src/MyAnimeList/MyAnimeList/Features/Seed/SeedDataHandler.cs
> +public class SeedDataHandler : IRequestHandler<SeedDataRequest, ResultOf<bool>>
trocar o nome da feature para Import e não Seed

2022-03-25 16:01 UTC, patrickhacens commented on src/MyAnimeList/MyAnimeList/Features/SomeFeature/GetSomeFeature/GetSomeFeatureHandler.cs
> +    public class GetSomeFeatureHandler : IRequestHandler<GetSomeFeatureRequest, ResultOf<SomeDTO>>
Depois tem que remover esse teste aqui

2022-03-28 11:34 UTC, demartinvinicius commented
Adicionado controller para realizar a importação dos dados.

2022-03-28 16:41 UTC, demartinvinicius commented on src/MyAnimeList/MyAnimeList/RawData/watching_status.csv
> +status, description
Foram retirados.

2022-03-28 16:43 UTC, demartinvinicius commented on src/MyAnimeList/MyAnimeList/Features/Seed/SeedDataHandler.cs
> +public class SeedDataHandler : IRequestHandler<SeedDataRequest, ResultOf<bool>>
Done

2022-03-28 17:18 UTC, patrickhacens requested changes

2022-03-28 17:18 UTC, patrickhacens commented on src/MyAnimeList/MyAnimeList/Features/Import/SeedDataHandler.cs
> +        using (var reader = new StreamReader("..\\..\\..\\RawData\\animelist.csv", Encoding.UTF8))
caminho para o arquivo deve ser informado através da request

2022-03-28 17:19 UTC, lucnascimento98 commented on src/MyAnimeList/MyAnimeList/Features/SomeFeature/GetSomeFeature/GetSomeFeatureHandler.cs
> +    public class GetSomeFeatureHandler : IRequestHandler<GetSomeFeatureRequest, ResultOf<SomeDTO>>
feito

2022-03-28 17:24 UTC, patrickhacens approved these changes
Não estou avaliando a parte de importação por que isso está em outra issue

2022-03-28 17:25 UTC, merged